#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="$ROOT_DIR/research/_meta/index.md"
INDEX_DIR="$ROOT_DIR/research/_meta/index"
STAGES=(00_inbox 01_active 02_reference 03_archive)

"$ROOT_DIR/scripts/reindex.sh" all >/dev/null

{
  echo "# Research Index"
  echo
  echo "Generated by scripts/reindex_all.sh."
  echo
  echo "This aggregate index is regenerated only for CI or final integration."
  echo "For normal work, update the relevant shard in research/_meta/index/."
  echo

  for stage in "${STAGES[@]}"; do
    shard="$INDEX_DIR/${stage}.md"
    if [[ ! -f "$shard" ]]; then
      echo "Missing shard: $shard" >&2
      exit 1
    fi
    sed -n '/^## /,$p' "$shard"
  done
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
